package com.inspiredpublicspeaking.speechcoach;

import android.content.Context;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Created by Chad Schultz on 1/19/2016.
 */
public class Criteria {
    // No need for this class to be instantiated
    private Criteria() {}

    public static List<EvaluationCriterionGroup> getCriteriaGroups(Context context) {
        List<EvaluationCriterionGroup> criteriaGroups = new ArrayList<EvaluationCriterionGroup>();

        EvaluationCriterionGroup group;
        List<EvaluationCriterion> criteria;
        EvaluationCriterion criterion;

        // Fill in with static data for now. In the future, may change this to fill in from JSON

        // TODO: use real rating data instead of random
        // TODO: or at least move the mock rating to the constructor

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_speaker_intro));
        group.setIconResId(R.drawable.ic_assignment_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_built_credibility));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_prepared_audience));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_speech_opening));
        group.setIconResId(R.drawable.ic_flight_takeoff_black_24px);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_attention_getting));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_relevant));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_confident));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_good_stuff));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_attitude));
        group.setIconResId(R.drawable.ic_face_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_confident));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_enthusiastic));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_appropriate_for_content));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_eye_contact));
        group.setIconResId(R.drawable.ic_visibility_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_all_of_audience));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_looked_in_the_eye));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_connected_for_seconds));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_voice));
        group.setIconResId(R.drawable.ic_record_voice_over_black_24px);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_conversational_style));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_good_volume));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_good_rate));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_clarity));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_varied));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_pauses));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_body_language));
        group.setIconResId(R.drawable.ic_accessibility_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_natural_gestures));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_varied_gestures));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_posture));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_stood_firm));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_moved_with_purpose));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_mini_stages));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_words));
        group.setIconResId(R.drawable.ic_spellcheck_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_smooth_delivery));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_word_choice));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_powerful_lines));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_grammar));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_know_your_audience));
        group.setIconResId(R.drawable.ic_event_seat_black_24px);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_appropriate_for_audience));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_built_rapport));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_visual_aids));
        group.setIconResId(R.drawable.ic_visibility_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_no_bad_visual_aids));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_did_not_distract));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_smoothly_handled));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_easily_visible));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_storytelling));
        group.setIconResId(R.drawable.ic_local_library_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_stories_made_points));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_distinct_characters));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_mental_imagery));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_act_it_out));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_speaker_exposed));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_humor));
        group.setIconResId(R.drawable.ic_mood_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_appropriate_humor));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_room_for_laughs));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_well_timed));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_research));
        group.setIconResId(R.drawable.ic_insert_chart_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_evidence));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_sources_credible));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_audience_interaction));
        group.setIconResId(R.drawable.ic_question_answer_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_multiple_forms_audience_interaction));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_comfortable));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_beneficial_audience_interaction));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_flexible));
        group.setIconResId(R.drawable.ic_swap_calls_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_dealt_with_disruptions));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_callback));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_recovered));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_responded_appropriately));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_structure));
        group.setIconResId(R.drawable.ic_format_list_numbered_24dp);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_clear_general_purpose));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_clear_specific_purpose));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_topic_size));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_points_support_purpose));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_valuable_lessons_taught));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_outline_easy_to_follow));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        group = new EvaluationCriterionGroup();
        group.setName(context.getString(R.string.criteria_group_name_speech_closing));
        group.setIconResId(R.drawable.ic_flight_land_black_24px);
        criteria = new ArrayList<EvaluationCriterion>();
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_bookended_opening));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_reminded_audience));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        criterion = new EvaluationCriterion();
        criterion.setName(context.getString(R.string.criterion_name_ended_strong));
        criterion.setRating(new Float(new Random().nextInt(6)));
        criteria.add(criterion);
        group.setCriteria(criteria);
        criteriaGroups.add(group);

        return criteriaGroups;
    }
}
